import fiveStars from "../img/icons/FiveStars.png";

export const reviews = [
  {
    id: 1,
    stars: fiveStars,
    alt: "Five stars",
    text: "If you  are looking for the best basement waterproofing company, then look no  further. The team at Royal Work Basement Waterproofing are the best in  class.",
    initials: "Cory Hubbell",
    fbLink: "https://facebook.com/",
  },
  {
    id: 2,
    stars: fiveStars,
    alt: "Five stars",
    text: "Service was amazing starting with estimate from Anatoliy, to the quality of the work when finished.... Highly recommend...",
    initials: "Chelsea Vieira",
    fbLink: "https://facebook.com/",
  },
  {
    id: 3,
    stars: fiveStars,
    alt: "Five stars",
    text: "I discovered a leak in the basement; Campany rep was very thorough to  find the source of the leak, and it was eliminated in a timely manner.",
    initials: "Anna Anna",
    fbLink: "https://facebook.com/",
  },
  {
    id: 4,
    stars: fiveStars,
    alt: "Five stars",
    text: "Vivamus dictum mi pharetra odio posuere hendrerit. Mauris nisl leo, rhoncus semper nulla vitae, interdum fermentum mi. Curabitur imperdiet euismod lectus, ac semper diam suscipit dictum. ",
    initials: "Lorem Ipsum",
    fbLink: "https://facebook.com/",
  },
  {
    id: 5,
    stars: fiveStars,
    alt: "Five stars",
    text: "Nunc nulla odio, sodales vitae interdum ut, ullamcorper nec lectus. Fusce porttitor laoreet orci, at facilisis massa rhoncus quis. Fusce luctus turpis eget purus euismod facilisis. Duis ex est, ornare at arcu sed, feugiat tristique eros.",
    initials: "Lorem Ipsum",
    fbLink: "https://facebook.com/",
  },
  {
    id: 6,
    stars: fiveStars,
    alt: "Five stars",
    text: "Vivamus dictum mi pharetra odio posuere hendrerit. Mauris nisl leo, rhoncus semper nulla vitae, interdum fermentum mi. Curabitur imperdiet euismod lectus, ac semper diam suscipit dictum. ",
    initials: "Lorem Ipsum",
    fbLink: "https://facebook.com/",
  },
  {
    id: 7,
    stars: fiveStars,
    alt: "Five stars",
    text: "Nunc nulla odio, sodales vitae interdum ut, ullamcorper nec lectus. Fusce porttitor laoreet orci, at facilisis massa rhoncus quis. Fusce luctus turpis eget purus euismod facilisis. Duis ex est, ornare at arcu sed, feugiat tristique eros.",
    initials: "Lorem Ipsum",
    fbLink: "https://facebook.com/",
  },
  {
    id: 8,
    stars: fiveStars,
    alt: "Five stars",
    text: "Vivamus dictum mi pharetra odio posuere hendrerit. Mauris nisl leo, rhoncus semper nulla vitae, interdum fermentum mi. Curabitur imperdiet euismod lectus, ac semper diam suscipit dictum. ",
    initials: "Lorem Ipsum",
    fbLink: "https://facebook.com/",
  },
  {
    id: 9,
    stars: fiveStars,
    alt: "Five stars",
    text: "Nunc nulla odio, sodales vitae interdum ut, ullamcorper nec lectus. Fusce porttitor laoreet orci, at facilisis massa rhoncus quis. Fusce luctus turpis eget purus euismod facilisis. Duis ex est, ornare at arcu sed, feugiat tristique eros.",
    initials: "Lorem Ipsum",
    fbLink: "https://facebook.com/",
  },
  {
    id: 10,
    stars: fiveStars,
    alt: "Five stars",
    text: "Nunc nulla odio, sodales vitae interdum ut, ullamcorper nec lectus. Fusce porttitor laoreet orci, at facilisis massa rhoncus quis. Fusce luctus turpis eget purus euismod facilisis. Duis ex est, ornare at arcu sed, feugiat tristique eros.",
    initials: "Lorem Ipsum",
    fbLink: "https://facebook.com/",
  },
];
